[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
VITE_API_URL = "${{ VITE_API_URL }}"
VITE_WS_URL = "${{ VITE_WS_URL }}"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
